# LLM prompt-labeling
DEEPINFRA_TOKEN=

# HF model loading
APP_CLASSIFIER_HF_REPO_ID=YOUR_ORG/YOUR_MODEL_REPO
APP_CLASSIFIER_REVISION=
APP_CLASSIFIER_HF_TOKEN=
APP_CLASSIFIER_TASK_CONFIG=configs/pdu.json
APP_CLASSIFIER_LABEL_MAPPING_PATH=

# Queue worker
QUEUE_URL=https://deepsee-queue.herokuapp.com/exchange-batch
QUEUE_API_KEY=
QUEUE_KEY=APP_CLASSIFIER_PLACEHOLDER
BATCH_SIZE=8
EMPTY_QUEUE_SLEEP_SECONDS=60

# Runtime
APP_CLASSIFIER_DEVICE=cuda
APP_CLASSIFIER_MAX_LENGTH=512
APP_CLASSIFIER_MODEL_BATCH_SIZE=8
APP_CLASSIFIER_LOAD_IN_4BIT=1
APP_CLASSIFIER_PREFER_BF16=1
